---
{{- if .Values.recommender.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scaleops.name" .Values.recommender }}
rules:
  - apiGroups:
      - analysis.scaleops.sh
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deployments/scale
      - replicasets/scale
      - replicationcontrollers/scale
      - statefulsets/scale
      - daemonsets/scale
    verbs:
      - get
      - list
      - watch
      - update
      - patch
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig"}}
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
      - update
      - patch
{{- end }}
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
      - cronjobs/scale
      - jobs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'autoscaling'
      - 'keda.sh'
    resources:
      - horizontalpodautoscalers
      - scaledobjects
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - 'karpenter.sh'
    resources:
      - provisioners
      - nodepools
      - nodeclaims
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
  - apiGroups:
      - 'metrics.k8s.io'
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - 'storage.k8s.io'
    resources:
      - csistoragecapacities
      - csidrivers
      - csinodes
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - patch
    resourceNames:
      - argocd-cm
  - apiGroups:
      - argoproj.io
    resources:
      - applications
      - applicationsets
      - argocds
      - rollouts
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
{{- end }}
