apiVersion: v1
kind: Service
metadata:
  name: {{ include "scaleops.fullname" (merge .Values.recommender (dict "Chart" .Chart "Release" .Release)) }}
  labels:
    {{- (include "scaleops.labels" (dict "Chart" .Chart "Release" .Release "nameOverride" .Values.recommender.nameOverride "image" .Values.recommender.image )) | nindent 4 }}
  annotations:
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.recommender.serviceType }}
  ports:
  {{- range $key, $serviceValues := .Values.recommender.services }}
    - name: {{ $key }}
      {{- toYaml $serviceValues | nindent 6}}
  {{- end }}
  selector:
    {{- (include "scaleops.selectorLabels" (dict "Chart" .Chart "Release" .Release "nameOverride" .Values.recommender.nameOverride "image" .Values.recommender.image )) | nindent 4 }}
