{{- if .Values.recommender.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleops.name" .Values.recommender }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- (include "scaleops.labels" (dict "Chart" .Chart "Release" .Release "nameOverride" .Values.recommender.nameOverride "image" .Values.recommender.image )) | nindent 4 }}
  {{- with .Values.recommender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
