{{- if .Values.scaleopsToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.imagePullSecretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
