- name: Delete DNS A Record
  hosts: dns
  gather_facts: no
  tasks:
    - name: Remove DNS A record - API
      win_dns_record:
        name: "{{ dns_name }}"
        type: A
        zone: "{{ dns_zone }}"
        state: absent
    
    - name: Remove DNS A record ingress - Ingress
      win_dns_record:
        name: "{{ dns_name_ingress }}"
        type: A
        zone: "{{ dns_zone }}"
        state: absent

