---
{{- if .Values.admissions.enabled }}
{{- if .Values.admissions.clusterRole.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "scaleops.name" .Values.admissions }}
rules:
  - apiGroups:
      - 'admissionregistration.k8s.io'
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - 'analysis.scaleops.sh'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - pods
      - replicationcontrollers
      - replicationcontrollers/scale
      - namespaces
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
      - replicasets
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deployments/scale
      - replicasets/scale
      - replicationcontrollers/scale
      - statefulsets/scale
      - daemonsets/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - 'autoscaling'
      - 'keda.sh'
    resources:
      - horizontalpodautoscalers
      - scaledobjects
    verbs:
      - get
      - list
      - watch
{{- if .Capabilities.APIVersions.Has "apps.openshift.io/v1/DeploymentConfig"}}
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs
    verbs:
      - get
      - list
      - watch
{{- end }}
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
      - cronjobs/scale
      - jobs/scale
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
