{{- if .Values.admissions.enabled -}}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: scaleops-mutating-webhook-configuration
{{- if .Values.admissions.tls.certificate }}
  annotations:
    cert-manager.io/inject-ca-from: scaleops-system/{{ .Values.admissions.tls.certificate }}
{{- end }}
webhooks:
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: {{ include "scaleops.fullname" (merge .Values.admissions (dict "Chart" .Chart "Release" .Release)) }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-rightsizing-scaleops-io-v1-pod
      port: {{ .Values.admissions.services.admission.port }}
  failurePolicy: Ignore
  name: namespace.rightsizing.scaleops.sh
  reinvocationPolicy: IfNeeded
  rules:
    - apiGroups:
        - ""
      apiVersions:
        - v1
      operations:
        - CREATE
      resources:
        - pods
    - apiGroups:
        - "autoscaling"
      apiVersions:
        - v2
      operations:
        - 'UPDATE'
      resources:
        - horizontalpodautoscalers
  sideEffects: None
{{- end }}