{{- $namespaces := list "kube-system" "karpenter" "cluster-autoscaler" }}

{{- range $namespace := $namespaces }}
{{- $ns := (lookup "v1" "Namespace" "" $namespace) }}
{{- if ($ns) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.Values.agent.rbac.rolesExternal.name }}
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ''
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
{{- end }}
---
{{- end }}