---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.agent.rbac.rolesInternal.name }}
  # bind in scaleops-system namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.agent.rbac.rolesInternal.name }}
subjects:
  - kind: ServiceAccount
    name: {{ include "scaleops.name" .Values.agent }}
    namespace: {{ .Release.Namespace }}
