{{- if .Values.prometheusOperatorIntegration }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaleops
spec:
  selector:
    matchLabels:
      scaleops.sh: "true"
  endpoints:
  - port: metrics
    honorLabels: true
{{- end }}
