---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "repo-updater.serviceAccountName" . }}
rules:
  - apiGroups:
      - analysis.scaleops.sh
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - patch
      - create
      - delete
