{{- if and .Values.rbac.create  -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
  name: {{ include ".prometheus.internalRoleName" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
{{- end }}
