{{- if .Values.global.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "prometheus.server.fullname" . }}
  namespace: {{ include "prometheus.namespace" . }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.server.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-dashboards
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-agent
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-recommender
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-updater
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-network-monitor
      ports:
        - port: 9090
          protocol: TCP
  egress:
{{- include "scaleops.egress-apiserver" . }}
{{- include "scaleops.egress-dns" . }}
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-recommender
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-agent
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-updater
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: kube-state-metrics
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: scaleops-network-monitor
      ports:
        - port: 8080
          protocol: TCP
{{- end }}
