{{- if .Values.global.enableNetworkMonitoring }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.networkMonitor.rbac.rolesInternal.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
{{- end }}