{{- if and .Values.global.enableNetworkMonitoring .Values.networkMonitor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scaleops.name" .Values.networkMonitor }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- (include "scaleops.labels" (dict "Chart" .Chart "Release" .Release "nameOverride" .Values.networkMonitor.nameOverride "image" .Values.networkMonitor.image )) | nindent 4 }}
  {{- with .Values.networkMonitor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
